language: node_js

node_js:
  - stable

install:
  - yarn install

script:
  - yarn cover

# Send coverage data to Coveralls
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn coveralls
